/*
ESTE ES UN REGISTRO DE LA COMPOSICION DE LA DB Y SUS RESTRICCIONES

LAS CATEGORIAS NO ESTÁN REGISTRADAS COMO CLAVE FORANEA
CON LA INTENCION DE QUE SE PUEDAN ALMACENAR VARIOS VALORES
SEPARADOS POR UNA COMA, EJECUTANDO UN EXPLODE EN LA PAGINA
PARA PODER LISTARLOS EN MAS DE UNA CATEGORIA, COSA QUE
ES UTIL, ESPECIALMENTE EN LAS BUSQUEDAS. 

DICHO ESPACIO ESTARÍA LLENO DE LOS ID, SEPARADOS POR COMAS
EJ:  1,2 ; CORRESPONDERÍA A ESTAR INCLUIDO EN LA CATEGORIA
1 Y 2
*/
CREATE DATABASE blog;

CREATE TABLE usuarios(
    id INT(255),
    nombre VARCHAR(255),
    mail VARCHAR(255),
    contraseña VARCHAR(255),
    fecha DATE,
    CONSTRAINT uq_usuarios UNIQUE(mail)
)

CREATE TABLE categorias(
    id INT(255),
    nombre VARCHAR(255),
    CONSTRAINT uq_categorias UNIQUE(nombre)
)

CREATE TABLE entradas(
    id INT(255),
    categorias varchar(255),
    usuario_id INT(255),
    titulo VARCHAR(255),
    entrada VARCHAR(255),
    fecha DATE,
    CONSTRAINT pk_entradas PRIMARY KEY (id),
    CONSTRAINT fk_usuarios_entradas FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
)





